language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
  - Gemfile-1.8.7
  - Gemfile-rails4
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
matrix:
  exclude:
    - gemfile: Gemfile
      rvm: 1.8.7
    - gemfile: Gemfile-rails4
      rvm: 1.8.7
    - gemfile: Gemfile-1.8.7
      rvm: 1.9.3
    - gemfile: Gemfile-1.8.7
      rvm: 2.0.0
  allow_failures:
    - { gemfile: Gemfile-rails4 }
